CREATE LOGIN [svc_inventory_manager_api]
    WITH PASSWORD = N'{INSERT_APPROPRIATE_PASSWORD_AND_DO_NOT_PERSIST_TO_REPO}', SID = 0xEFC4A40BC750E34E812787DAA108FAD1, DEFAULT_DATABASE = [InventoryManagement], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

