CREATE LOGIN [svc_inventory_management_dev]
    WITH PASSWORD = N'{INSERT_APPROPRIATE_PASSWORD_AND_DO_NOT_PERSIST_TO_REPO}', SID = 0x332616EE573E1E49833EBF921B1295DA, DEFAULT_DATABASE = [InventoryManagement], DEFAULT_LANGUAGE = [us_english];

