DECLARE @subscriptionID INT = 20;

EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Green Bell Pepper',
		@description='Organic preferred';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Yellow Onion',
		@description='Organic preferred';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Napa Cabbage',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Peanuts',
		@description='50 % Salted';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Almonds',
		@description='50 % Salted';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Maple Syrup',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Olive Oil',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Black Peppercorns',
		@description='Whole';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Kleenex',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Toilet Paper',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Paper Towels',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Paper Towels',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Swifter Sheets',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Laundry Detergent',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Dryer Sheets',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Mouthwash',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Toothpaste',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Dental Floss',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Claritin',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Liquid Hand Soap',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Dishwasher Detergent',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Lemons',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Apples',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Limes',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Avacadoes',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Beer (IPA)',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Beer (Lager)',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Red Wine',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='White Wine',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Bourbon',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Gin',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Sparkling Water',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Bar Soap',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Light Bulbs',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Clorox Bleach Wipes',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='White Vinegar',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Coffee',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Yogurt (Greek)',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Cheese (String)',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Cheddar Cheese',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Sour Cream',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Salsa',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Lasagna Noodles',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Diced Tomatoes',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Quinoa',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Black Beans',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Kidney Beans',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Chicken Breasts',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Ground Turkey',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Salmon',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Cream Cheese',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Tortillas',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Hummus',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Ice Cream',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Crackers',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Mustard (Brown)',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Eggs',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Bacon (Turkey)',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Hash Browns',
		@description='';
EXEC  [dbo].[upsertItem] @subscriptionID=@subscriptionID,
		@name='Potato (red)',
		@description='';