-- Categories
IF NOT EXISTS(SELECT [id] FROM [stock].[Category] WHERE [name] = 'Food')
	INSERT INTO [stock].[Category]([name]) VALUES('Food')
IF NOT EXISTS(SELECT [id] FROM [stock].[Category] WHERE [name] = 'Cleaning Supplies')
	INSERT INTO [stock].[Category]([name]) VALUES('Cleaning Supplies')
IF NOT EXISTS(SELECT [id] FROM [stock].[Category] WHERE [name] = 'Toiletries')
	INSERT INTO [stock].[Category]([name]) VALUES('Toiletries')
IF NOT EXISTS(SELECT [id] FROM [stock].[Category] WHERE [name] = 'Tools')
	INSERT INTO [stock].[Category]([name]) VALUES('Tools')
IF NOT EXISTS(SELECT [id] FROM [stock].[Category] WHERE [name] = 'Entertainment')
	INSERT INTO [stock].[Category]([name]) VALUES('Entertainment')
IF NOT EXISTS(SELECT [id] FROM [stock].[Category] WHERE [name] = 'Clothing')
	INSERT INTO [stock].[Category]([name]) VALUES('Clothing')
SELECT * FROM [stock].[Category]
-- Sub-Categories
--		--	FOOD
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Dairy and Eggs' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Dairy and Eggs')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Fresh Produce' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Fresh Produce')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Sauces and Condiments' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Sauces and Condiments')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Freezer' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Freezer')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Herbs and Spices' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Herbs and Spices')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Baking Supplies' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Baking Supplies')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Oil and Vinegar' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Oil and Vinegar')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Special Seasonings' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Special Seasonings')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Canned and Jarred Goods' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Canned and Jarred Goods')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Packaged Goods' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Packaged Goods')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Pasta and Rice' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Pasta and Rice')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Storage and Cooking Aids' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Storage and Cooking Aids')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Sweeteners' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Sweeteners')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Nuts and Seeds' AND [category_id] = 1)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(1, 'Nuts and Seeds')

--		--	Cleaning Supplies
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Laundry' AND [category_id] = 2)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(2, 'Laundry')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Bathroom' AND [category_id] = 2)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(2, 'Bathroom')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'General Purpose' AND [category_id] = 2)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(2, 'General Purpose')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Automobile' AND [category_id] = 2)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(2, 'Automobile')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Kitchen' AND [category_id] = 2)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(2, 'Kitchen')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Outdoor' AND [category_id] = 2)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(2, 'Outdoor')
--		--	Toiletries
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Dental Care' AND [category_id] = 3)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(3, 'Dental Care')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Eye Care' AND [category_id] = 3)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(3, 'Eye Care')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Personal Hygiene' AND [category_id] = 3)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(3, 'Personal Hygiene')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Medications' AND [category_id] = 3)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(3, 'Medications')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Skin Care' AND [category_id] = 3)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(3, 'Skin Care')
IF NOT EXISTS(SELECT [id] FROM [stock].[SubCategory] WHERE [name] = 'Soap and Shampoo' AND [category_id] = 3)
	INSERT INTO [stock].[SubCategory]( [category_id], [name]) VALUES(3, 'Soap and Shampoo')

SELECT sc.[id], sc.[name] AS SubCategory, c.[id] AS CategoryID, c.[name] AS CategoryName FROM 
[stock].[SubCategory] sc INNER
JOIN [stock].[Category] c 
 ON c.id = sc.category_id

 --ITEMS: Food
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Eggs' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Eggs')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Almond Milk' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Almond Milk')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Soy Milk' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Soy Milk')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Whole Milk' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Whole Milk')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = '2% Milk' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, '2% Milk')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Half and Half' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Half and Half')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Whipping Cream' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Whipping Cream')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Salted Butter' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Salted Butter')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Unsalted Butter' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Unsalted Butter')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Greek Yogurt' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Greek Yogurt')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Goat Cheese' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Goat Cheese')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Feta Cheese' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Feta Cheese')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Cheddar Cheese' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Cheddar Cheese')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Parmesan Cheese' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Parmesan Cheese')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Mozzarella  Cheese' AND [category_id] = 1 AND [sub_category_id] = 1)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 1, 'Mozzarella  Cheese')
 --ITEMS: Food	-- Fresh Produce
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Carrots' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Carrots')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Apples' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Apples')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Avocados' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Avocados')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Bananas' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Bananas')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Bell peppers' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Bell peppers')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Broccoli' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Broccoli')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Cauliflower' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Cauliflower')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Celery' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Celery')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Lemons' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Lemons')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Limes' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Limes')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Spinach' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Spinach')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Kale' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Kale')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Chard' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Chard')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Romaine Lettuce' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Romaine Lettuce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Iceberg Lettuce' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Iceberg Lettuce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Cilantro' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Cilantro')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Flat-leaf parsley' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Flat-leaf parsley')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Scallions' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Scallions')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Garlic' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Garlic')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Ginger' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Ginger')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Potatoes (Russet)' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Potatoes (Russet)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Potatoes (Red)' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Potatoes (Red)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Potatoes (Yellow)' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Potatoes (Yellow)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Potatoes (Sweet)' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Potatoes (Sweet)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Onions' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Onions')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Tomatoes (Cherry)' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Tomatoes (Cherry)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Tomatoes (Grape)' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Tomatoes (Grape)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Tomatoes (Beefsteak)' AND [category_id] = 1 AND [sub_category_id] = 2)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 2, 'Tomatoes (Beefsteak)')

 --ITEMS: Food	-- Sauces and Condiments
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Strawberry Jelly/Jam/Preserves' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Strawberry Jelly/Jam/Preserves')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Rasberry Jelly/Jam/Preserves' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Rasberry Jelly/Jam/Preserves')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Blueberry Jelly/Jam/Preserves' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Blueberry Jelly/Jam/Preserves')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Ketchup' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Ketchup')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Mayonnaise' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Mayonnaise')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Mustard (Yellow)' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Mustard (Yellow)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Mustard (Brown)' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Mustard (Brown)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Mustard (Dijon)' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Mustard (Dijon)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Pickles' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Pickles')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Sriracha Sauce' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Sriracha Sauce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Tabasco Sauce' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Tabasco Sauce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Worcestershire Sauce' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Worcestershire Sauce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Soy Sauce' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Soy Sauce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Fish Sauce' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Fish Sauce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Alfredo Sauce' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Alfredo Sauce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Spaghetti Sauce' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Spaghetti Sauce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Steak Sauce' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Steak  Sauce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Teriyaki  Sauce' AND [category_id] = 1 AND [sub_category_id] = 3)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 3, 'Teriyaki  Sauce')

 --ITEMS: Food	-- Freezer
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Ice Cream' AND [category_id] = 1 AND [sub_category_id] = 4)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 4, 'Ice Cream')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Popsicles' AND [category_id] = 1 AND [sub_category_id] = 4)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 4, 'Popsicles')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Bacon' AND [category_id] = 1 AND [sub_category_id] = 4)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 4, 'Bacon')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Sausage Patties' AND [category_id] = 1 AND [sub_category_id] = 4)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 4, 'Sausage Patties')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Hash Browns' AND [category_id] = 1 AND [sub_category_id] = 4)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 4, 'Hash Browns')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Chicken Breasts' AND [category_id] = 1 AND [sub_category_id] = 4)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 4, 'Chicken Breasts')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Pastry Dough' AND [category_id] = 1 AND [sub_category_id] = 4)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 4, 'Pastry Dough')

 --ITEMS: Food	-- Herbs and Spices
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Pepper (Black)' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Pepper (Black)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Pepper (Red)' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Pepper (Red)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Salt (Sea)' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Salt (Sea)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Salt (Kosher)' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Salt (Kosher)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Salt (Fine)' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Salt (Fine)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Bay Leaves' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Bay Leaves')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Cayenne  Pepper' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Cayenne  Pepper')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Curry Powder' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Curry Powder')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Garlic Powder' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Garlic Powder')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Tumeric' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Tumeric')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Fennel Seed' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Fennel Seed')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Ground Cinnamon' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Ground Cinnamon')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Ground Cloves' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Ground Cloves')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Ground Ginger' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Ground Ginger')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Ground Cumin' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Ground Cumin')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Oregano' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Oregano')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Rosemary' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Rosemary')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Thyme' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Thyme')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Paprika' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Paprika')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Onion Powder' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Onion Powder')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Nutmeg' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Nutmeg')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Marjoram' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Marjoram')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Chili Powder' AND [category_id] = 1 AND [sub_category_id] = 5)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 5, 'Chili Powder')

 --ITEMS: Food	-- Baking Supplies
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Flour (All-Purpose)' AND [category_id] = 1 AND [sub_category_id] = 6)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 6, 'Flour (All-Purpose)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Baking Soda' AND [category_id] = 1 AND [sub_category_id] = 6)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 6, 'Baking Soda')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Cocoa Powder' AND [category_id] = 1 AND [sub_category_id] = 6)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 6, 'Cocoa Powder')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Chocolate Chips' AND [category_id] = 1 AND [sub_category_id] = 6)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 6, 'Chocolate Chips')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Evaportated Milk' AND [category_id] = 1 AND [sub_category_id] = 6)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 6, 'Evaportated Milk')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Vanilla Extract' AND [category_id] = 1 AND [sub_category_id] = 6)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 6, 'Vanilla Extract')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Lemon Extract' AND [category_id] = 1 AND [sub_category_id] = 6)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 6, 'Lemon Extract')

 --ITEMS: Food	-- Oil and Vinegar
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Balsamic Vinegar' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Balsamic Vinegar')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Canola Oil' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Canola Oil')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Olive Oil' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Olive Oil')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Avacado Oil' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Avacado Oil')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Sesame Oil' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Sesame Oil')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Coconut Oil' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Coconut Oil')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Vegetable  Oil' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Vegetable  Oil')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'White Cooking Wine' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'White Cooking Wine')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Red Cooking Wine' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Red Cooking Wine')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'White Vinegar' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'White Vinegar')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Apple Cider Vinegar' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Apple Cider Vinegar')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Red Wine Vinegar' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Red Wine Vinegar')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Rice Vinegar' AND [category_id] = 1 AND [sub_category_id] = 7)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 7, 'Rice Vinegar')

 --ITEMS: Food	-- Special Seasonings
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Chili Mix' AND [category_id] = 1 AND [sub_category_id] = 8)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 8, 'Chili Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Gravy Packets' AND [category_id] = 1 AND [sub_category_id] = 8)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 8, 'Gravy Packets')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Marinade Mix' AND [category_id] = 1 AND [sub_category_id] = 8)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 8, 'Marinade Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Salad Dressing Mix' AND [category_id] = 1 AND [sub_category_id] = 8)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 8, 'Salad Dressing Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Stew Mix' AND [category_id] = 1 AND [sub_category_id] = 8)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 8, 'Stew Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Taco Seasoning' AND [category_id] = 1 AND [sub_category_id] = 8)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 8, 'Taco Seasoning')

 --ITEMS: Food	-- Nuts and Seeds
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Almonds' AND [category_id] = 1 AND [sub_category_id] = 26)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 26, 'Almonds')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Peanuts' AND [category_id] = 1 AND [sub_category_id] = 26)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 26, 'Peanuts')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Cashews' AND [category_id] = 1 AND [sub_category_id] = 26)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 26, 'Cashews')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Macadamia Nuts' AND [category_id] = 1 AND [sub_category_id] = 26)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 26, 'Macadamia Nuts')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Pine Nuts' AND [category_id] = 1 AND [sub_category_id] = 26)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 26, 'Pine Nuts')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Mixed Nuts' AND [category_id] = 1 AND [sub_category_id] = 26)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 26, 'Mixed Nuts')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Walnuts' AND [category_id] = 1 AND [sub_category_id] = 26)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 26, 'Walnuts')

 --ITEMS: Food	-- Canned and Jarred Goods
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Chicken Broth' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Chicken Broth')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Black)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Black)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Kidney)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Kidney)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Chickpea)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Chickpea)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Green)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Green)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Cannellini)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Cannellini)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Lima)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Lima)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Red)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Red)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Baked)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Baked)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Navy)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Navy)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Beans (Pinto)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Beans (Pinto)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Corn (Canned)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Corn (Canned)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Artichoke (Canned)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Artichoke (Canned)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Olives (Black)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Olives (Black)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Tomatoes (Canned)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Tomatoes (Canned)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Tuna (Canned)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Tuna (Canned)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Tomato Paste' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Tomato Paste')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Jalepenos (Can/Jar)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Jalepenos (Can/Jar)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Peanut Butter' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Peanut Butter')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Applesauce' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Applesauce')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Peaches (Canned)' AND [category_id] = 1 AND [sub_category_id] = 9)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 9, 'Peaches (Canned)')

 --ITEMS: Food	-- Packaged Goods
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Brownie Mix' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Brownie Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Cake Mix' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Cake Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Hot Chocolate Mix' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Hot Chocolate Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Muffin Mix' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Muffin Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Pancake Mix' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Pancake Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Suffing Mix' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Stuffing Mix')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Cereal' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Cereal')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Crackers' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Crackers')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Coffee' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Coffee')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Oatmeal' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Oatmeal')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Pretzels' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Pretzels')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Popcorn' AND [category_id] = 1 AND [sub_category_id] = 10)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 10, 'Popcorn')

 --ITEMS: Food	-- Pasta and Rice
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Angel Hair Pasta' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Angel Hair Pasta')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Brown Rice' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Brown Rice')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'White Rice' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'White Rice')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Elbow Macaroni' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Elbow Macaroni')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Fettucini' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Fettucini')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Lasagna Noodles' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Lasagna Noodles')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Spaghetti Noodles' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Spaghetti Noodles')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Polenta' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Polenta')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Bulgur' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Bulger')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Couscous' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Couscous')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Quinoa' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Quinoa')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Breadcrumbs' AND [category_id] = 1 AND [sub_category_id] = 11)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 11, 'Breadcrumbs')

 --ITEMS: Food	-- Storage and Cooking Aids
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Aluminum Foil' AND [category_id] = 1 AND [sub_category_id] = 12)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 12, 'Aluminum Foil')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Ziploc Bags' AND [category_id] = 1 AND [sub_category_id] = 12)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 12, 'Ziploc Bags')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Plastic Wrap' AND [category_id] = 1 AND [sub_category_id] = 12)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 12, 'Plastic Wrap')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Wax Paper' AND [category_id] = 1 AND [sub_category_id] = 12)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 12, 'Wax Paper')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Parchment Paper' AND [category_id] = 1 AND [sub_category_id] = 12)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 12, 'Parchment Paper')

 --ITEMS: Food	-- Sweeteners
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Honey' AND [category_id] = 1 AND [sub_category_id] = 13)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 13, 'Honey')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Sugar (White Granulated)' AND [category_id] = 1 AND [sub_category_id] = 13)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 13, 'Sugar (White Granulated)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Sugar (Brown)' AND [category_id] = 1 AND [sub_category_id] = 13)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 13, 'Sugar (Brown)')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Agave Nectar' AND [category_id] = 1 AND [sub_category_id] = 13)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 13, 'Agave Nectar')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Maple Syrup' AND [category_id] = 1 AND [sub_category_id] = 13)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(1, 13, 'Maple Syrup')


-- Cleaning Supplies
 --ITEMS: Cleaning Supplies	-- Laundry
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Laundry Detergent' AND [category_id] = 2 AND [sub_category_id] = 14)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(2, 14, 'Laundry Detergent')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Dryer Sheets' AND [category_id] = 2 AND [sub_category_id] = 14)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(2, 14, 'Dryer Sheets')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Oxyclean' AND [category_id] = 2 AND [sub_category_id] = 14)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(2, 14, 'Oxyclean')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Laundry Softener' AND [category_id] = 2 AND [sub_category_id] = 14)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(2, 14, 'Laundry Softener')
	
 --ITEMS: Cleaning Supplies	-- Bathroom
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Bleach' AND [category_id] = 2 AND [sub_category_id] = 15)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(2, 15, 'Bleach')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Disinfectant Spray Cleaner' AND [category_id] = 2 AND [sub_category_id] = 15)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(2, 15, 'Disinfectant Spray Cleaner')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Toilet Brush' AND [category_id] = 2 AND [sub_category_id] = 15)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(2, 15, 'Toilet Brush')

 --ITEMS: Cleaning Supplies	-- General Purpose
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Glass Cleaner' AND [category_id] = 2 AND [sub_category_id] = 16)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(2, 16, 'Glass Cleaner')
IF NOT EXISTS(SELECT [id] FROM [stock].[Item] WHERE [name] = 'Surface Spray Cleaner' AND [category_id] = 2 AND [sub_category_id] = 16)
	INSERT INTO [stock].[Item]( [category_id], [sub_category_id], [name]) VALUES(2, 16, 'Surface Spray Cleaner')




SELECT	category.[name], subCategory.[name], item.name, 
		item.id,category.[id], subCategory.[id]
FROM	[stock].[SubCategory] subCategory INNER
JOIN	[stock].[Category] category 
 ON		category.id = subCategory.category_id Inner
 JOIN	[stock].Item item 
 ON		item.category_id = category.id AND item.sub_category_id = subCategory.id
 ORDER	BY category.id ASC, subCategory.name ASC, item.name ASC
  FOR
      JSON AUTO

--------------------

SELECT	category.[name], subCategory.[name], item.name,-- COUNT(item.id) AS itemCount,
		item.id,category.[id], subCategory.[id]
FROM	[stock].[SubCategory] subCategory INNER
JOIN	[stock].[Category] category 
 ON		category.id = subCategory.category_id Inner
 JOIN	[stock].Item item 
 ON		item.category_id = category.id AND item.sub_category_id = subCategory.id
 --GROUP	BY item.id, category.[name], subCategory.[name], item.name, category.id, subCategory.id
 ORDER	BY category.id ASC, subCategory.name ASC, item.name ASC


	  /*

SELECT	category.[name] [name], subCategory.[name] AS 'subCategory.name', item.[name] AS 'item.name', 
		item.id AS 'item.id',category.[id] AS 'id', item.sub_category_id  AS 'subCategory.id'
FROM	[stock].[SubCategory] subCategory INNER
JOIN	[stock].[Category] category 
 ON		category.id = subCategory.category_id Inner
 JOIN	[stock].Item item 
 ON		item.category_id = category.id AND item.sub_category_id = subCategory.id
 ORDER	BY category.id ASC, subCategory.name ASC, item.name ASC
  FOR
      JSON PATH
	  */

	  exec  [stock].[getItems] 